### PR TITLE
Ft password reset 157029245

### PR DESCRIPTION
**Pull request by Rodgers-M**
**What does this PR do?**
Enables a user to reset there Passwords .

**Description of tasks to be completed:**
  - create components to help user provide email and reset password
  - Implement sending email, password and conforamation token to the sever for verification

**How can this be tested manually?**
- with the latest changes, navigate to login, click  reset password and follow instructions.
- You can also use the Review app of this PR on heroku [rodgerevents](https://rodgerevents-pr-7.herokuapp.com/)

**Relevant tecker stories.**
-  157029245

**Screenshots**
**User email**
screen shot 2018-06-21 at 1 30 23 pm

**Link sent to user email**
screen shot 2018-06-21 at 1 41 38 pm

**Token confirmation loader**
screen shot 2018-06-21 at 1 35 04 pm

**Get new password**
screen shot 2018-06-21 at 1 35 51 pm

### CODE REVIEW

**Comment by ghost** [comment]
+1 on:
- Demo link.
- Catching errors and displaying descriptive error messages.
- Loaders don't take too long.
- Reset password works.

check:
- Check for grammatical errors in the text sent in the email.

**Comment by Rodgers-M** [comment]
@EdwardMudaida Thanks, will check and correct that.

**Review by betsybeth — CHANGES_REQUESTED** [review]
Comment are important to explain what is going on in each scope.

**Comment by Rodgers-M** [comment]
@betsybeth thanks, will add more comments where necessary

**Comment by betsybeth** [comment]
Okay, welcome

**Comment by MarloneA** [comment]
Good work, functionality works fine, I like that you've taken advantage of Heroku pipelines, makes it easier to test your code.

**Pull request merged**
